import type { RankTest } from '../../schema/RankTest';

export const BLUES_RANK_TESTS: RankTest[] = [
  {
    id: 'blues-rank-test-beginner-novice',
    archetypeId: 'blues',
    fromRank: 'beginner',
    toRank: 'novice',
    label: 'Beginner Gate: Blues Foundations',
    songTitle: 'Red House — Intro Groove',
    description:
      'Show that you understand the 12-bar form and can navigate the blues scale in the box position with basic expression.',
    techniques: [
      { name: '12-Bar Blues Form', branch: 'harmony-chords', nodeId: 'blues-001' },
      { name: 'Blues Scale Box Position', branch: 'fretboard-theory', nodeId: 'blues-002' },
      { name: 'Dominant 7th Chords', branch: 'harmony-chords', nodeId: 'blues-001' },
    ],
    nodeIds: ['blues-001', 'blues-002'],
    passingScore: 0.70,
    exercises: [
      {
        id: 'ex-blues-rank-bg-1',
        type: 'technique',
        prompt: 'Play a 12-bar blues in A using A7, D7, E7. Keep steady quarter-note strums. Repeat for 3 full choruses without losing your place in the form.',
        bpm: 70,
        bpmStart: 55,
        bpmGoal: 80,
        durationSeconds: 90,
        xpValue: 60,
        focusPoints: [
          'Feel the 4-bar "sentences": 4 bars of I, 2 of IV, 2 of I, 2 of V–IV–I',
          'Count "one two three four" quietly so you never lose the downbeat',
          'The V chord (E7) at bar 9 is your landmark — own that moment',
        ],
        selfAssessment: true,
      },
      {
        id: 'ex-blues-rank-bg-2',
        type: 'performance',
        prompt: 'Improvise a simple 8-bar melody using only the A blues scale box position over an A7 drone. Keep phrases short — 2–3 notes at a time.',
        bpm: 75,
        durationSeconds: 60,
        xpValue: 60,
        focusPoints: [
          'Start phrases on the root (A) or fifth (E) so they sound grounded',
          'Leave space — silence between phrases is part of the music',
          'The blue note (Eb) creates tension — use it sparingly for impact',
        ],
        selfAssessment: true,
      },
    ],
  },

  {
    id: 'blues-rank-test-novice-intermediate',
    archetypeId: 'blues',
    fromRank: 'novice',
    toRank: 'intermediate',
    label: 'Novice Gate: Sweet Home Alabama Riff',
    songTitle: 'Sweet Home Alabama — Main Riff',
    description:
      'Demonstrate string bending, shuffle feel, and the ability to combine rhythm and lead ideas in a blues-rock context.',
    techniques: [
      { name: 'String Bending (whole-step)', branch: 'technique', nodeId: 'blues-003' },
      { name: 'Shuffle Rhythm', branch: 'rhythm-timing', nodeId: 'blues-004' },
      { name: 'D / C / G Open Chords', branch: 'harmony-chords', nodeId: 'blues-001' },
      { name: 'Alternate Picking', branch: 'technique', nodeId: 'blues-003' },
      { name: 'Hammer-on & Pull-off', branch: 'technique' },
      { name: '8th-Note Feel', branch: 'rhythm-timing' },
    ],
    nodeIds: ['blues-001', 'blues-002', 'blues-003', 'blues-004'],
    passingScore: 0.75,
    exercises: [
      {
        id: 'ex-blues-rank-ni-1',
        type: 'technique',
        prompt: 'Play the D–C–G chord riff with the signature hammer-on fill on the D chord. Use alternate picking throughout. Repeat 4 times.',
        bpm: 80,
        bpmStart: 60,
        bpmGoal: 100,
        durationSeconds: 60,
        xpValue: 70,
        focusPoints: [
          'The hammer-on lands precisely on the "and" of beat 2 — not before or after',
          'Alternate pick: down on the beat, up on the "and"',
          'G chord should ring full and open after the busier D–C passage',
        ],
        selfAssessment: true,
      },
      {
        id: 'ex-blues-rank-ni-2',
        type: 'performance',
        prompt: 'Play a full 12-bar blues in A at a shuffle feel (long-short eighth notes). Include at least one whole-step bend that lands in tune.',
        bpm: 85,
        durationSeconds: 90,
        xpValue: 80,
        focusPoints: [
          'Shuffle feel: the "and" of each beat lands late, almost on the last third of the beat',
          'Use 2–3 fingers stacked behind your bending finger for strength and control',
          'Target the pitch of the 9th fret when bending from the 7th — fret it first to hear where you\'re going',
        ],
        selfAssessment: true,
      },
    ],
  },

  {
    id: 'blues-rank-test-intermediate-expert',
    archetypeId: 'blues',
    fromRank: 'intermediate',
    toRank: 'expert',
    label: 'Intermediate Gate: Texas Blues',
    songTitle: 'Pride and Joy — Rhythm & Lead',
    description:
      'Demonstrate the Texas shuffle groove and expressive blues soloing with vibrato and double-stop bends.',
    techniques: [
      { name: 'Texas Shuffle (sixth-based riff)', branch: 'rhythm-timing', nodeId: 'blues-006' },
      { name: 'Vibrato on Sustained Notes', branch: 'technique', nodeId: 'blues-007' },
      { name: 'Double-Stop Bends', branch: 'technique', nodeId: 'blues-005' },
      { name: 'Call and Response Phrasing', branch: 'lead-improvisation', nodeId: 'blues-008' },
    ],
    nodeIds: ['blues-005', 'blues-006', 'blues-007', 'blues-008'],
    passingScore: 0.78,
    exercises: [
      {
        id: 'ex-blues-rank-ie-1',
        type: 'technique',
        prompt: 'Play the Texas shuffle pattern (chord sixth intervals, boogie bass) for 2 choruses of 12-bar blues at a medium tempo.',
        bpm: 90,
        bpmStart: 70,
        bpmGoal: 110,
        durationSeconds: 90,
        xpValue: 90,
        focusPoints: [
          'The shuffle pairs a root note with the sixth — let the sixth ring clean',
          'Your pick hand should feel locked to the drummer — body moving with the groove',
          'Keep the groove even: rushing on the V chord is the most common mistake',
        ],
        selfAssessment: true,
      },
      {
        id: 'ex-blues-rank-ie-2',
        type: 'performance',
        prompt: 'Improvise a 12-bar solo with intentional call-and-response. Play a 2-bar phrase, leave 2 bars of space, answer it. End with vibrato on the final note.',
        bpm: 85,
        durationSeconds: 90,
        xpValue: 110,
        focusPoints: [
          'Phrase and rest equally — the space is as important as the notes',
          'Vibrato: even, controlled oscillation driven from the wrist, not the finger',
          'Answer each phrase with something melodically related — tell a story',
        ],
        selfAssessment: true,
      },
    ],
  },

  {
    id: 'blues-rank-test-expert-pro',
    archetypeId: 'blues',
    fromRank: 'expert',
    toRank: 'pro',
    label: 'Expert Gate: Full Blues Expression',
    songTitle: 'The Thrill Is Gone — Extended Solo',
    description:
      'Prove total command of the blues vocabulary: dynamics, minor blues tonality, turnarounds, and emotional storytelling across a full song form.',
    techniques: [
      { name: 'Minor Blues Tonality', branch: 'fretboard-theory', nodeId: 'blues-010' },
      { name: 'Turnaround Licks', branch: 'lead-improvisation', nodeId: 'blues-011' },
      { name: 'Dynamic Shaping (pp to ff)', branch: 'lead-improvisation', nodeId: 'blues-012' },
      { name: 'Across-Position Playing', branch: 'fretboard-theory' },
    ],
    nodeIds: ['blues-009', 'blues-010', 'blues-011', 'blues-012'],
    passingScore: 0.82,
    exercises: [
      {
        id: 'ex-blues-rank-ep-1',
        type: 'technique',
        prompt: 'Play a turnaround lick (bars 11–12 of the 12-bar form) in Bm that uses a descending chromatic movement back to the I chord. Repeat cleanly 8 times.',
        bpm: 75,
        bpmStart: 60,
        bpmGoal: 90,
        durationSeconds: 60,
        xpValue: 100,
        focusPoints: [
          'The turnaround must land on beat 1 of the next chorus — count carefully',
          'Descending chromatic lines need even timing — no rushing toward the root',
          'Each note should have its own weight — don\'t slide through them',
        ],
        selfAssessment: true,
      },
      {
        id: 'ex-blues-rank-ep-2',
        type: 'performance',
        prompt: 'Perform a 2-chorus solo (24 bars) over a Bm blues. Start barely audible, swell to a peak around bar 16, and resolve softly. Your dynamics should tell a story.',
        bpm: 70,
        durationSeconds: 120,
        xpValue: 150,
        focusPoints: [
          'Touch the string lightly at the start — barely any pick attack',
          'Peak intensity around bar 16: bends, vibrato, slightly more aggressive picking',
          'Resolution: one clean sustained note with slow vibrato — let it breathe',
        ],
        selfAssessment: true,
      },
    ],
  },
];
