import type { RankTest } from '../../schema/RankTest';

export const VAIDEOLOGY_RANK_TESTS: RankTest[] = [
  {
    id: 'vaideology-rank-test-beginner-novice',
    archetypeId: 'vaideology',
    fromRank: 'beginner',
    toRank: 'novice',
    label: 'Beginner Gate: Legato Foundation',
    songTitle: 'The Audience Is Listening — Opening Legato Run',
    description:
      'Show that your fretting-hand strength and independence can sustain a smooth legato phrase — no pick re-articulation, just hammer-ons and pull-offs.',
    techniques: [
      { name: 'Hammer-on Chains', branch: 'technique', nodeId: 'vaideology-001' },
      { name: 'Pull-off Chains', branch: 'technique', nodeId: 'vaideology-001' },
      { name: 'Left-Hand Independence', branch: 'technique' },
    ],
    nodeIds: ['vaideology-001', 'vaideology-002'],
    passingScore: 0.70,
    exercises: [
      {
        id: 'ex-vai-rank-bg-1',
        type: 'technique',
        prompt: 'Play a 4-note legato pattern (e.g., 5h7h9h10, then 10p9p7p5) on the B string continuously for 60 seconds. Only pick the first note — everything else is hammer-ons and pull-offs.',
        bpm: 70,
        bpmStart: 55,
        bpmGoal: 90,
        durationSeconds: 60,
        xpValue: 60,
        focusPoints: [
          'The first pick attack is the only pick — everything else is pure left-hand strength',
          'Drop the hammering finger from a height with force — it must produce a note equal to the picked note',
          'Pull-offs: flick the string sideways as the finger lifts — don\'t just lift',
        ],
        selfAssessment: true,
      },
      {
        id: 'ex-vai-rank-bg-2',
        type: 'performance',
        prompt: 'Play a 4-bar legato melody moving across 3 strings using only hammer-ons and pull-offs. The line should sound continuous — no breaks or silence from weak notes.',
        bpm: 65,
        durationSeconds: 60,
        xpValue: 60,
        focusPoints: [
          'Volume consistency is the test — every note in the chain must be the same volume',
          'Crossing strings: keep the fretting hand arched so you don\'t accidentally mute adjacent strings',
          'Listen critically: any dead or weak note is a technique gap to address',
        ],
        selfAssessment: true,
      },
    ],
  },

  {
    id: 'vaideology-rank-test-novice-intermediate',
    archetypeId: 'vaideology',
    fromRank: 'novice',
    toRank: 'intermediate',
    label: 'Novice Gate: Interval Control',
    songTitle: 'For the Love of God — Intro Sustained Intervals',
    description:
      'Demonstrate expressive control over wide intervals and sustained notes with vibrato and emotional phrasing in the Vai style.',
    techniques: [
      { name: 'Wide Interval Stretches', branch: 'fretboard-theory', nodeId: 'vaideology-003' },
      { name: 'Whammy Bar Controlled Vibrato', branch: 'technique', nodeId: 'vaideology-004' },
      { name: 'Emotional Phrasing (singing tone)', branch: 'lead-improvisation', nodeId: 'vaideology-005' },
      { name: '4th & 5th Interval Patterns', branch: 'music-theory' },
    ],
    nodeIds: ['vaideology-003', 'vaideology-004', 'vaideology-005'],
    passingScore: 0.75,
    exercises: [
      {
        id: 'ex-vai-rank-ni-1',
        type: 'technique',
        prompt: 'Play a slow, ascending pattern using perfect 4th intervals across all 6 strings. Each interval should ring fully — no muffled notes from wide stretches.',
        bpm: 55,
        bpmStart: 45,
        bpmGoal: 72,
        durationSeconds: 60,
        xpValue: 70,
        focusPoints: [
          'Wide stretches: keep your thumb behind the neck for maximum reach, not wrapped over',
          'Every note in the interval must ring simultaneously — test each pair by plucking both strings',
          'Move slowly between positions — don\'t sacrifice tone for speed',
        ],
        selfAssessment: true,
      },
      {
        id: 'ex-vai-rank-ni-2',
        type: 'performance',
        prompt: 'Improvise a slow 8-bar melody in E minor using only sustained notes with whammy-bar vibrato. Think of each note as a word in a sentence — make it mean something.',
        bpm: 50,
        durationSeconds: 90,
        xpValue: 80,
        focusPoints: [
          'Whammy vibrato: gentle oscillation of the bar — not a dive, just a shimmer',
          'Leave long spaces between notes — Vai\'s power comes from what he doesn\'t play',
          'Each note should have a reason to exist — aim for emotional weight, not filler',
        ],
        selfAssessment: true,
      },
    ],
  },

  {
    id: 'vaideology-rank-test-intermediate-expert',
    archetypeId: 'vaideology',
    fromRank: 'intermediate',
    toRank: 'expert',
    label: 'Intermediate Gate: Exotic Scales & Precision',
    songTitle: 'Passion and Warfare — Middle Eastern Passage',
    description:
      'Navigate exotic scale patterns (Lydian, Phrygian Dominant) with precise intonation and expressive delivery in Vai\'s signature compositional style.',
    techniques: [
      { name: 'Lydian Mode', branch: 'fretboard-theory', nodeId: 'vaideology-006' },
      { name: 'Phrygian Dominant Scale', branch: 'fretboard-theory', nodeId: 'vaideology-007' },
      { name: 'Precise Intonation on Exotic Intervals', branch: 'ear-training', nodeId: 'vaideology-008' },
      { name: 'Compositional Phrasing (thematic development)', branch: 'lead-improvisation' },
    ],
    nodeIds: ['vaideology-006', 'vaideology-007', 'vaideology-008'],
    passingScore: 0.78,
    exercises: [
      {
        id: 'ex-vai-rank-ie-1',
        type: 'technique',
        prompt: 'Play the Phrygian Dominant scale in E (E F G# A B C D E) ascending and descending 4 times. The b2 (F) and #3 (G#) are the signature intervals — hit them in tune.',
        bpm: 75,
        bpmStart: 60,
        bpmGoal: 95,
        durationSeconds: 60,
        xpValue: 85,
        focusPoints: [
          'The b2 interval (E to F, one fret) is microtonal in sound — make it deliberate and expressive',
          'The #3 (augmented second from F to G#) is the exotic leap — don\'t rush over it',
          'Use the scale melodically, not just as a technical exercise — let it sound Arabic/flamenco',
        ],
        selfAssessment: true,
      },
      {
        id: 'ex-vai-rank-ie-2',
        type: 'performance',
        prompt: 'Compose and perform a 16-bar solo that uses a single melodic theme stated in bar 1–2, then developed and varied through bar 16. Stay within one exotic scale.',
        bpm: 70,
        durationSeconds: 90,
        xpValue: 115,
        focusPoints: [
          'Thematic development: take a 3–4 note idea and transform it — invert it, extend it, vary the rhythm',
          'The listener should hear the theme return — compositional intent separates Vai from pure improvisation',
          'Dynamic arc: quiet theme statement, louder variations, dramatic resolution',
        ],
        selfAssessment: true,
      },
    ],
  },

  {
    id: 'vaideology-rank-test-expert-pro',
    archetypeId: 'vaideology',
    fromRank: 'expert',
    toRank: 'pro',
    label: 'Expert Gate: The Vai Universe',
    songTitle: 'Tender Surrender — Full Performance',
    description:
      'Deliver a complete, expressive performance of Steve Vai\'s most emotionally demanding ballad — demonstrating total technique mastery in service of feeling.',
    techniques: [
      { name: 'Full Technique Integration', branch: 'technique', nodeId: 'vaideology-009' },
      { name: 'Orchestral-Style Guitar Phrasing', branch: 'lead-improvisation', nodeId: 'vaideology-010' },
      { name: 'Emotional Dynamics (whisper to scream)', branch: 'lead-improvisation', nodeId: 'vaideology-011' },
      { name: 'Compositional Architecture (full song)', branch: 'music-theory', nodeId: 'vaideology-012' },
    ],
    nodeIds: ['vaideology-009', 'vaideology-010', 'vaideology-011', 'vaideology-012'],
    passingScore: 0.82,
    exercises: [
      {
        id: 'ex-vai-rank-ep-1',
        type: 'technique',
        prompt: 'Play the Tender Surrender verse melody with full expressive phrasing — every note bent or vibratoed to a specific pitch, no note played "straight." Run for 90 seconds.',
        bpm: 58,
        bpmStart: 48,
        bpmGoal: 68,
        durationSeconds: 90,
        xpValue: 100,
        focusPoints: [
          'Expressive playing means EVERY note is shaped — no neutral, unintentional notes',
          'Approach important notes from below (bend up) or shake them with vibrato — never just "plunk" them',
          'Listen to the original — Vai treats the guitar like a human voice throughout',
        ],
        selfAssessment: true,
      },
      {
        id: 'ex-vai-rank-ep-2',
        type: 'performance',
        prompt: 'Perform the full Tender Surrender solo section (or an original piece in the same emotional vocabulary). Begin in a whisper, let it build organically to a screaming climax, then resolve to silence.',
        bpm: 60,
        durationSeconds: 180,
        xpValue: 150,
        focusPoints: [
          'The arc: intimacy → yearning → anguish → catharsis → peace. Let each phase breathe',
          'Silence is a technique — the pauses have as much weight as the notes',
          'At the peak, every technical skill you\'ve learned should be available — but use only what serves the emotion',
        ],
        selfAssessment: true,
      },
    ],
  },
];
