import type { RankTest } from '../../schema/RankTest';

export const JAZZ_RANK_TESTS: RankTest[] = [
  {
    id: 'jazz-rank-test-beginner-novice',
    archetypeId: 'jazz',
    fromRank: 'beginner',
    toRank: 'novice',
    label: 'Beginner Gate: Shell Voicings',
    songTitle: 'Autumn Leaves — Basic Chord Changes',
    description:
      'Demonstrate you can voice basic jazz chords (shell voicings) and follow a standard chord progression with correct rhythm.',
    techniques: [
      { name: 'Shell Voicings (root–3rd–7th)', branch: 'harmony-chords', nodeId: 'jazz-001' },
      { name: 'Chord Rhythm (Freddie Green style)', branch: 'rhythm-timing' },
      { name: 'Major & Minor 7th Chords', branch: 'harmony-chords', nodeId: 'jazz-002' },
    ],
    nodeIds: ['jazz-001', 'jazz-002'],
    passingScore: 0.70,
    exercises: [
      {
        id: 'ex-jazz-rank-bg-1',
        type: 'technique',
        prompt: 'Play Cm7 and F7 shell voicings (root on low E or A string) with a smooth ii–V connection. Repeat 8 times with no pausing.',
        bpm: 60,
        bpmStart: 50,
        bpmGoal: 75,
        durationSeconds: 60,
        xpValue: 60,
        focusPoints: [
          'Shell voicings: root, 3rd, 7th only — no 5th needed',
          'The voice leading from 3rd of Cm7 to 7th of F7 is only a half step — keep it smooth',
          'Mute strings above the voicing — jazz guitar is clean and selective',
        ],
        selfAssessment: true,
      },
      {
        id: 'ex-jazz-rank-bg-2',
        type: 'performance',
        prompt: 'Play through the Autumn Leaves ii–V–I progression (Dm7–G7–Cmaj7) in whole notes, one chord per bar. Repeat 4 times.',
        bpm: 70,
        durationSeconds: 60,
        xpValue: 60,
        focusPoints: [
          'The ii–V–I is the most common jazz movement — internalize how it resolves',
          'Let each chord ring clearly for the full measure before moving',
          'Listen for the bass note: it should be the lowest note you play',
        ],
        selfAssessment: true,
      },
    ],
  },

  {
    id: 'jazz-rank-test-novice-intermediate',
    archetypeId: 'jazz',
    fromRank: 'novice',
    toRank: 'intermediate',
    label: 'Novice Gate: Jazz Comping',
    songTitle: 'There Will Never Be Another You — Full Comping',
    description:
      'Show rhythmic comping with chord embellishments, anticipations, and voice-led movement through a jazz standard.',
    techniques: [
      { name: 'Chord Anticipation (landing before the beat)', branch: 'rhythm-timing', nodeId: 'jazz-005' },
      { name: 'Drop-2 Voicings', branch: 'harmony-chords', nodeId: 'jazz-003' },
      { name: 'Guide Tone Movement', branch: 'music-theory', nodeId: 'jazz-004' },
      { name: 'Dominant 7th Color Tones (b9, #11)', branch: 'harmony-chords' },
    ],
    nodeIds: ['jazz-003', 'jazz-004', 'jazz-005'],
    passingScore: 0.75,
    exercises: [
      {
        id: 'ex-jazz-rank-ni-1',
        type: 'technique',
        prompt: 'Play a ii–V–I in C major using drop-2 voicings, with the Dm7 landing an eighth note early (anticipated). Repeat 8 times.',
        bpm: 70,
        bpmStart: 55,
        bpmGoal: 90,
        durationSeconds: 60,
        xpValue: 70,
        focusPoints: [
          'Anticipation: the chord change happens an eighth note before beat 1, not on it',
          'Drop-2: take the 2nd voice from the top and drop it an octave lower',
          'Track the 3rd and 7th — they are the "guide tones" that define each chord',
        ],
        selfAssessment: true,
      },
      {
        id: 'ex-jazz-rank-ni-2',
        type: 'performance',
        prompt: 'Comp through 2 choruses of a 32-bar jazz standard (AABA form). Vary the rhythm each A section — no two comp patterns the same.',
        bpm: 80,
        durationSeconds: 120,
        xpValue: 80,
        focusPoints: [
          'Comping supports the melody/soloist — leave space and don\'t overplay',
          'Vary your voicings: sometimes top melody in the chord, sometimes inner voice',
          'The B section (bridge) often goes to a different key center — don\'t miss it',
        ],
        selfAssessment: true,
      },
    ],
  },

  {
    id: 'jazz-rank-test-intermediate-expert',
    archetypeId: 'jazz',
    fromRank: 'intermediate',
    toRank: 'expert',
    label: 'Intermediate Gate: Bebop Soloing',
    songTitle: 'Donna Lee — Head & Solo',
    description:
      'Navigate fast-moving jazz changes using bebop scales, chord-tone targeting, and articulate single-note phrasing.',
    techniques: [
      { name: 'Bebop Major Scale', branch: 'fretboard-theory', nodeId: 'jazz-006' },
      { name: 'Chord-Tone Targeting on Downbeats', branch: 'music-theory', nodeId: 'jazz-007' },
      { name: 'Chromatic Approach Notes', branch: 'lead-improvisation', nodeId: 'jazz-008' },
      { name: 'Across-the-Barline Phrasing', branch: 'lead-improvisation' },
    ],
    nodeIds: ['jazz-006', 'jazz-007', 'jazz-008'],
    passingScore: 0.78,
    exercises: [
      {
        id: 'ex-jazz-rank-ie-1',
        type: 'technique',
        prompt: 'Play the C bebop major scale (C D E F G G# A B C) ascending and descending in eighth notes. The added chromatic tone keeps chord tones on downbeats.',
        bpm: 80,
        bpmStart: 60,
        bpmGoal: 100,
        durationSeconds: 60,
        xpValue: 85,
        focusPoints: [
          'Chord tones (root, 3rd, 5th, 7th) land on beats — chromatic passing tones land on "ands"',
          'Articulate with light pick attack — jazz single notes have a singing, horn-like quality',
          'Use alternate picking throughout — consistency builds speed naturally',
        ],
        selfAssessment: true,
      },
      {
        id: 'ex-jazz-rank-ie-2',
        type: 'performance',
        prompt: 'Improvise over a Cmaj7–Am7–Dm7–G7 loop for 4 minutes. Include at least one chromatic approach note into each chord change.',
        bpm: 90,
        durationSeconds: 120,
        xpValue: 115,
        focusPoints: [
          'Chromatic approach: arrive at a chord tone from a half-step below or above',
          'Target the 3rd or 7th on beat 1 of each chord — these notes tell the listener which chord you\'re on',
          'Phrase across bar lines — jazz sentences don\'t always start on beat 1',
        ],
        selfAssessment: true,
      },
    ],
  },

  {
    id: 'jazz-rank-test-expert-pro',
    archetypeId: 'jazz',
    fromRank: 'expert',
    toRank: 'pro',
    label: 'Expert Gate: Chord-Melody Mastery',
    songTitle: 'All The Things You Are — Chord Melody',
    description:
      'Arrange and perform a complete jazz standard as a chord-melody solo guitar piece — melody in the top voice, chord accompaniment underneath.',
    techniques: [
      { name: 'Chord-Melody Arrangement', branch: 'harmony-chords', nodeId: 'jazz-011' },
      { name: 'Reharmonization', branch: 'music-theory', nodeId: 'jazz-010' },
      { name: 'Rubato Phrasing', branch: 'lead-improvisation', nodeId: 'jazz-012' },
      { name: 'Extended Chord Voicings (9ths, 13ths)', branch: 'harmony-chords', nodeId: 'jazz-009' },
    ],
    nodeIds: ['jazz-009', 'jazz-010', 'jazz-011', 'jazz-012'],
    passingScore: 0.82,
    exercises: [
      {
        id: 'ex-jazz-rank-ep-1',
        type: 'technique',
        prompt: 'Play the first 8 bars of All The Things You Are as a chord melody. The melody note must be the highest note in each chord voicing.',
        bpm: 55,
        bpmStart: 45,
        bpmGoal: 65,
        durationSeconds: 90,
        xpValue: 100,
        focusPoints: [
          'The melody must sing on top — louder than any other note in the chord',
          'Use your thumb to pluck the bass note and fingers for the chord if needed',
          'Moving chord shapes: the melody note often forces a non-standard voicing — find it',
        ],
        selfAssessment: true,
      },
      {
        id: 'ex-jazz-rank-ep-2',
        type: 'performance',
        prompt: 'Perform the full AABA form of All The Things You Are as solo guitar chord melody. Apply rubato to the melody — let it breathe and sing.',
        bpm: 60,
        durationSeconds: 150,
        xpValue: 150,
        focusPoints: [
          'Rubato: the melody can lead or lag slightly behind the implied beat — like a singer',
          'Reharmonize at least 2 chords with a substitution of your choice',
          'The final chord should be a lush extended voicing (9th or 13th) — make it shimmer',
        ],
        selfAssessment: true,
      },
    ],
  },
];
