import type { Achievement } from '../schema/Achievement';

export const ACHIEVEMENTS: Achievement[] = [
  {
    id: 'first-note',
    label: 'First Note',
    description: 'Complete your very first skill node.',
    icon: '🎸',
    xpBonus: 50,
    condition: { type: 'nodes-completed', value: 1 },
  },
  {
    id: 'warming-up',
    label: 'Warming Up',
    description: 'Complete 5 skill nodes.',
    icon: '🔥',
    xpBonus: 75,
    condition: { type: 'nodes-completed', value: 5 },
  },
  {
    id: 'committed',
    label: 'Committed',
    description: 'Complete 10 skill nodes.',
    icon: '⚡',
    xpBonus: 100,
    condition: { type: 'nodes-completed', value: 10 },
  },
  {
    id: 'halfway',
    label: 'Halfway There',
    description: 'Complete 20 skill nodes across any tree.',
    icon: '🏅',
    xpBonus: 150,
    condition: { type: 'nodes-completed', value: 20 },
  },
  {
    id: 'level-5',
    label: 'Level 5',
    description: 'Reach level 5.',
    icon: '⭐',
    xpBonus: 100,
    condition: { type: 'level-reached', value: 5 },
  },
  {
    id: 'level-10',
    label: 'Level 10',
    description: 'Reach level 10.',
    icon: '🌟',
    xpBonus: 200,
    condition: { type: 'level-reached', value: 10 },
  },
  {
    id: 'level-20',
    label: 'Level 20',
    description: 'Reach level 20.',
    icon: '💫',
    xpBonus: 400,
    condition: { type: 'level-reached', value: 20 },
  },
  {
    id: 'first-test',
    label: 'Test Taker',
    description: 'Pass your first tier gate test.',
    icon: '📝',
    xpBonus: 150,
    condition: { type: 'tier-test-passed', value: 1 },
  },
  {
    id: 'xp-500',
    label: 'Getting Started',
    description: 'Earn 500 total XP.',
    icon: '💰',
    xpBonus: 50,
    condition: { type: 'xp-total', value: 500 },
  },
  {
    id: 'xp-2000',
    label: 'Dedicated Learner',
    description: 'Earn 2000 total XP.',
    icon: '💎',
    xpBonus: 200,
    condition: { type: 'xp-total', value: 2000 },
  },
  {
    id: 'tree-master',
    label: 'Tree Master',
    description: 'Complete every node in a skill tree.',
    icon: '👑',
    xpBonus: 500,
    condition: { type: 'tree-completed', value: 1 },
  },

  // ── Rank milestone achievements ──────────────────────────────────────────
  {
    id: 'rank-novice',
    label: 'Finding Your Voice',
    description: 'Reach Novice rank in any archetype.',
    icon: '🌱',
    xpBonus: 100,
    condition: { type: 'rank-achieved', value: 0, rankValue: 'novice' },
  },
  {
    id: 'rank-intermediate',
    label: 'Getting Serious',
    description: 'Reach Intermediate rank in any archetype.',
    icon: '🔥',
    xpBonus: 200,
    condition: { type: 'rank-achieved', value: 0, rankValue: 'intermediate' },
  },
  {
    id: 'rank-expert',
    label: 'Seasoned Player',
    description: 'Reach Expert rank in any archetype.',
    icon: '⚡',
    xpBonus: 350,
    condition: { type: 'rank-achieved', value: 0, rankValue: 'expert' },
  },
  {
    id: 'rank-pro',
    label: 'Guitar Hero',
    description: 'Reach Pro rank in any archetype.',
    icon: '🎸',
    xpBonus: 600,
    condition: { type: 'rank-achieved', value: 0, rankValue: 'pro' },
  },
  {
    id: 'test-out-novice',
    label: 'Fast Learner',
    description: 'Pass a Novice rank gate test to skip ahead.',
    icon: '⚡',
    xpBonus: 150,
    condition: { type: 'rank-test-passed', value: 1 },
  },
  {
    id: 'test-out-intermediate',
    label: 'Shortcut Artist',
    description: 'Pass an Intermediate rank gate test.',
    icon: '🏃',
    xpBonus: 200,
    condition: { type: 'rank-test-passed', value: 2 },
  },
  {
    id: 'test-out-expert',
    label: 'The Real Deal',
    description: 'Pass an Expert rank gate test.',
    icon: '💎',
    xpBonus: 300,
    condition: { type: 'rank-test-passed', value: 3 },
  },
  {
    id: 'renaissance-player',
    label: 'Renaissance Player',
    description: 'Reach Novice rank in 3 or more archetypes.',
    icon: '🌟',
    xpBonus: 250,
    condition: { type: 'archetypes-at-rank', value: 3, rankValue: 'novice' },
  },
  {
    id: 'speed-demon',
    label: 'Speed Demon',
    description: 'Hit the target BPM goal in a BPM Challenge exercise.',
    icon: '🚀',
    xpBonus: 100,
    condition: { type: 'bpm-goal-hit', value: 1 },
  },
];
