import type { RankTest } from '../../schema/RankTest';

export const METAL_RANK_TESTS: RankTest[] = [
  {
    id: 'metal-rank-test-beginner-novice',
    archetypeId: 'metal',
    fromRank: 'beginner',
    toRank: 'novice',
    label: 'Beginner Gate: Metal Fundamentals',
    songTitle: 'Iron Man — Main Riff',
    description:
      'Demonstrate controlled palm muting, downstroke power, and the ability to execute a heavy riff with consistent tone.',
    techniques: [
      { name: 'Palm Muting', branch: 'technique', nodeId: 'metal-001' },
      { name: 'Downstroke Power Chords', branch: 'harmony-chords', nodeId: 'metal-002' },
      { name: 'Steady Eighth-Note Timing', branch: 'rhythm-timing' },
    ],
    nodeIds: ['metal-001', 'metal-002'],
    passingScore: 0.70,
    exercises: [
      {
        id: 'ex-metal-rank-bg-1',
        type: 'technique',
        prompt: 'Play the Iron Man main riff using strict downstrokes with palm muting on the single notes. Every muted note should sound even and controlled.',
        bpm: 60,
        bpmStart: 50,
        bpmGoal: 75,
        durationSeconds: 60,
        xpValue: 60,
        focusPoints: [
          'Palm muting: rest the very edge of your pick hand on the saddle — not too far forward',
          'Downstroke only — consistency of attack is more important than speed here',
          'Let the power chord at the end of each phrase ring open (no mute) for contrast',
        ],
        selfAssessment: true,
      },
      {
        id: 'ex-metal-rank-bg-2',
        type: 'performance',
        prompt: 'Play the full Iron Man riff (intro + verse pattern) 4 complete times without stopping. Keep the tempo and the muting consistent throughout.',
        bpm: 70,
        durationSeconds: 60,
        xpValue: 60,
        focusPoints: [
          'The riff is syncopated — feel where beat 1 is, even during the gaps',
          'Your pick attack should be firm and even — no accidental accents or dropouts',
          'Listen to your tone: it should sound tight and controlled, not sloppy',
        ],
        selfAssessment: true,
      },
    ],
  },

  {
    id: 'metal-rank-test-novice-intermediate',
    archetypeId: 'metal',
    fromRank: 'novice',
    toRank: 'intermediate',
    label: 'Novice Gate: Alternate Picking at Speed',
    songTitle: 'Master of Puppets — Main Riff',
    description:
      'Prove you can alternate pick a tight, low-string riff at metal tempo with controlled palm muting and consistent downstroke/upstroke balance.',
    techniques: [
      { name: 'Alternate Picking (down-up)', branch: 'technique', nodeId: 'metal-003' },
      { name: 'Chromatic Patterns', branch: 'fretboard-theory', nodeId: 'metal-004' },
      { name: 'Dynamic Palm Muting (tight vs. open)', branch: 'technique', nodeId: 'metal-001' },
      { name: '16th-Note Rhythmic Accuracy', branch: 'rhythm-timing', nodeId: 'metal-005' },
    ],
    nodeIds: ['metal-001', 'metal-003', 'metal-004', 'metal-005'],
    passingScore: 0.75,
    exercises: [
      {
        id: 'ex-metal-rank-ni-1',
        type: 'technique',
        prompt: 'Alternate pick the Master of Puppets main riff (E–E–E–G–Gb chromatic descent) with palm muting. Keep each pick stroke identical in attack — down and up should sound the same.',
        bpm: 80,
        bpmStart: 60,
        bpmGoal: 110,
        durationSeconds: 60,
        xpValue: 70,
        focusPoints: [
          'Upstrokes in metal must match downstrokes in attack — practice slowly to equalize them',
          'Wrist motion only — arm involvement slows you down at higher BPMs',
          'Keep the palm mute consistent through the chromatic descent — pressure doesn\'t change',
        ],
        selfAssessment: true,
      },
      {
        id: 'ex-metal-rank-ni-2',
        type: 'performance',
        prompt: 'Play the full verse riff of Master of Puppets 4 consecutive times at target tempo. No fumbling the chromatic pull-offs at the end of each phrase.',
        bpm: 100,
        durationSeconds: 60,
        xpValue: 80,
        focusPoints: [
          'The pull-off at the riff\'s end is a left-hand technique — your fretting fingers do the work, not the pick',
          'Stay relaxed: tension above 100 BPM causes mistakes — breathe, loosen your grip',
          'Listen to the groove, not just the notes — lock with an imaginary kick drum',
        ],
        selfAssessment: true,
      },
    ],
  },

  {
    id: 'metal-rank-test-intermediate-expert',
    archetypeId: 'metal',
    fromRank: 'intermediate',
    toRank: 'expert',
    label: 'Intermediate Gate: Shred Foundations',
    songTitle: 'Eruption (Van Halen) — Two-Hand Tapping',
    description:
      'Execute two-hand tapping cleanly, demonstrating independent left and right hand coordination and the ability to maintain a melodic phrase through the technique.',
    techniques: [
      { name: 'Two-Hand Tapping', branch: 'technique', nodeId: 'metal-006' },
      { name: 'Legato Runs (HOPO chains)', branch: 'technique', nodeId: 'metal-007' },
      { name: 'Pentatonic Tapping Patterns', branch: 'fretboard-theory', nodeId: 'metal-008' },
      { name: 'Rhythmic Accuracy at Speed', branch: 'rhythm-timing' },
    ],
    nodeIds: ['metal-006', 'metal-007', 'metal-008'],
    passingScore: 0.78,
    exercises: [
      {
        id: 'ex-metal-rank-ie-1',
        type: 'technique',
        prompt: 'Execute a 3-note tapping pattern (tap-pull-hammer: e.g., 12t-8h-5p) repeatedly on the B string for 60 seconds. All 3 notes must sound at equal volume.',
        bpm: 80,
        bpmStart: 60,
        bpmGoal: 110,
        durationSeconds: 60,
        xpValue: 85,
        focusPoints: [
          'Tapping finger: use the pick edge or middle finger — strike firmly at the fret, not between frets',
          'Pull-off: flick the string sideways as you remove the tapping finger to produce the next note',
          'Hammer-on: left-hand finger drops with force — the note should ring without picking',
        ],
        selfAssessment: true,
      },
      {
        id: 'ex-metal-rank-ie-2',
        type: 'performance',
        prompt: 'Perform a 16-bar tapping passage using at least 3 different string-set patterns. Maintain even volume across all positions.',
        bpm: 90,
        durationSeconds: 90,
        xpValue: 115,
        focusPoints: [
          'Move positions cleanly — the shift between string sets is the hardest part',
          'Speed comes from efficiency: minimize the tap and pull-off motion, not maximize force',
          'Listen for even volume: weak hammer-ons are the #1 tell of untrained tapping',
        ],
        selfAssessment: true,
      },
    ],
  },

  {
    id: 'metal-rank-test-expert-pro',
    archetypeId: 'metal',
    fromRank: 'expert',
    toRank: 'pro',
    label: 'Expert Gate: Full Shred Mastery',
    songTitle: 'Tornado of Souls — Extended Solo',
    description:
      'Execute a full advanced metal solo with sweep arpeggios, legato runs, whammy-bar dive bombs, and pinch harmonics — all while maintaining musical intent.',
    techniques: [
      { name: 'Sweep Picking Arpeggios', branch: 'technique', nodeId: 'metal-010' },
      { name: 'Pinch Harmonics', branch: 'technique', nodeId: 'metal-009' },
      { name: 'Whammy Bar Technique', branch: 'technique', nodeId: 'metal-011' },
      { name: 'Full Solo Composition', branch: 'lead-improvisation', nodeId: 'metal-012' },
    ],
    nodeIds: ['metal-009', 'metal-010', 'metal-011', 'metal-012'],
    passingScore: 0.82,
    exercises: [
      {
        id: 'ex-metal-rank-ep-1',
        type: 'technique',
        prompt: 'Play a 5-string sweep arpeggio (Dm shape, ascending and descending) cleanly at BPM goal. Roll each fretting finger so notes don\'t bleed together.',
        bpm: 80,
        bpmStart: 60,
        bpmGoal: 110,
        durationSeconds: 60,
        xpValue: 100,
        focusPoints: [
          '5-string sweep: one direction of the pick, one direction of the chord roll',
          'Roll the fretting fingers in sequence — each note muted by the rolling motion as the next sounds',
          'The top and bottom notes anchor the arpeggio — they must be the loudest',
        ],
        selfAssessment: true,
      },
      {
        id: 'ex-metal-rank-ep-2',
        type: 'performance',
        prompt: 'Perform a 90-second improvised metal solo incorporating sweep arpeggios, a legato run, one pinch harmonic, and a whammy-bar dive. Build from moderate intensity to peak.',
        bpm: 110,
        durationSeconds: 90,
        xpValue: 150,
        focusPoints: [
          'The solo needs structure: setup → tension → release. Don\'t just shred from bar 1',
          'Pinch harmonic: pick edge + thumb simultaneously touches the string right after picking',
          'Dive bomb: depress whammy slowly for a controlled descent — jerky dives sound amateurish',
        ],
        selfAssessment: true,
      },
    ],
  },
];
