import type { RankTest } from '../../schema/RankTest';

export const COUNTRY_RANK_TESTS: RankTest[] = [
  {
    id: 'country-rank-test-beginner-novice',
    archetypeId: 'country',
    fromRank: 'beginner',
    toRank: 'novice',
    label: 'Beginner Gate: Country Strumming',
    songTitle: 'Take Me Home, Country Roads — Chord Progression',
    description:
      'Demonstrate basic country chord changes with a simple down-up strum pattern and clean open chord fretting.',
    techniques: [
      { name: 'Open Chords (G, C, D, Em)', branch: 'harmony-chords', nodeId: 'country-001' },
      { name: 'Down-Up Strum Pattern', branch: 'rhythm-timing', nodeId: 'country-002' },
      { name: 'Chord Transitions in Time', branch: 'rhythm-timing' },
    ],
    nodeIds: ['country-001', 'country-002'],
    passingScore: 0.70,
    exercises: [
      {
        id: 'ex-country-rank-bg-1',
        type: 'technique',
        prompt: 'Strum the Take Me Home, Country Roads progression (G–Em–C–D) with a basic down-down-up-down-up pattern. Keep it smooth and in time.',
        bpm: 70,
        bpmStart: 55,
        bpmGoal: 85,
        durationSeconds: 60,
        xpValue: 60,
        focusPoints: [
          'The "boom-chick" feel: emphasize downstrokes on beats 1 and 3',
          'Make chord changes slightly before the beat — not on it — to stay in the groove',
          'All strings should ring clear: press your fingertips close to the fret wire',
        ],
        selfAssessment: true,
      },
      {
        id: 'ex-country-rank-bg-2',
        type: 'performance',
        prompt: 'Play the full verse progression (G–Em–C–D) 4 complete times through without stopping. Count the beats aloud if needed.',
        bpm: 75,
        durationSeconds: 60,
        xpValue: 60,
        focusPoints: [
          'Count 1-2-3-4 on the beat if you feel yourself rushing or dragging',
          'The Em chord often catches beginners — know it cold before starting',
          'Strum with your wrist, not your whole arm — smaller movement = more control',
        ],
        selfAssessment: true,
      },
    ],
  },

  {
    id: 'country-rank-test-novice-intermediate',
    archetypeId: 'country',
    fromRank: 'novice',
    toRank: 'intermediate',
    label: 'Novice Gate: Chicken Picking',
    songTitle: 'Hot Rod Lincoln — Country Picking Pattern',
    description:
      'Demonstrate the hybrid picking "chicken picking" technique — combining flatpick and fingers for a snappy, percussive country texture.',
    techniques: [
      { name: 'Hybrid Picking (pick + middle finger)', branch: 'technique', nodeId: 'country-003' },
      { name: 'String Snapping (chicken pick)', branch: 'technique', nodeId: 'country-004' },
      { name: 'Pentatonic Runs in Country Context', branch: 'fretboard-theory', nodeId: 'country-005' },
      { name: 'Alternating Bass Lines', branch: 'rhythm-timing' },
    ],
    nodeIds: ['country-003', 'country-004', 'country-005'],
    passingScore: 0.75,
    exercises: [
      {
        id: 'ex-country-rank-ni-1',
        type: 'technique',
        prompt: 'Play a G major arpeggio using hybrid picking: flatpick on the low G (6th string), middle finger on B, ring finger on high E. Snap each finger string with a snappy upward flick.',
        bpm: 80,
        bpmStart: 60,
        bpmGoal: 100,
        durationSeconds: 60,
        xpValue: 70,
        focusPoints: [
          'The snap comes from curling the finger quickly — the nail or flesh flicks the string upward',
          'Keep the flatpick on the bass strings while the fingers handle the treble strings',
          'The "cluck" sound is the goal — it should sound punchy and defined, not smooth',
        ],
        selfAssessment: true,
      },
      {
        id: 'ex-country-rank-ni-2',
        type: 'performance',
        prompt: 'Play a 12-bar country shuffle in G using alternating bass (root–fifth) with flatpick and chicken-pick fills on beats 2 and 4.',
        bpm: 90,
        durationSeconds: 60,
        xpValue: 80,
        focusPoints: [
          'Bass alternates: root on beat 1, fifth on beat 3 — this is the country "boom-chick" engine',
          'Fills on 2 and 4: a quick pentatonic riff or single snapped note answers the bass',
          'The whole thing should feel like a train moving — steady, driving, inevitable',
        ],
        selfAssessment: true,
      },
    ],
  },

  {
    id: 'country-rank-test-intermediate-expert',
    archetypeId: 'country',
    fromRank: 'intermediate',
    toRank: 'expert',
    label: 'Intermediate Gate: Telecaster Twang Lead',
    songTitle: 'Country Boy Can Survive — Lead Solo',
    description:
      'Execute a full country lead solo using double stops, pedal steel bends, and blazing pentatonic runs in the style of classic Telecaster players.',
    techniques: [
      { name: 'Pedal Steel Bends (oblique bends)', branch: 'technique', nodeId: 'country-006' },
      { name: 'Double Stops (thirds, sixths)', branch: 'harmony-chords', nodeId: 'country-007' },
      { name: 'Country Pentatonic Runs', branch: 'lead-improvisation', nodeId: 'country-008' },
      { name: 'Open-String Licks', branch: 'fretboard-theory' },
    ],
    nodeIds: ['country-006', 'country-007', 'country-008'],
    passingScore: 0.78,
    exercises: [
      {
        id: 'ex-country-rank-ie-1',
        type: 'technique',
        prompt: 'Execute a pedal steel bend: hold the B string bent up a whole step while plucking the high E string open. Then release the bend. Repeat 8 times in tune.',
        bpm: 70,
        bpmStart: 55,
        bpmGoal: 90,
        durationSeconds: 60,
        xpValue: 85,
        focusPoints: [
          'The bent note (B string) must stay in tune while the open E rings above it',
          'Use 2 or 3 fingers stacked on the B string for bending strength',
          'This is an oblique bend — only the lower string moves, the upper stays open',
        ],
        selfAssessment: true,
      },
      {
        id: 'ex-country-rank-ie-2',
        type: 'performance',
        prompt: 'Improvise a 16-bar country lead solo using double stops, at least one pedal steel bend, and a 4-note pentatonic run. The whole thing should bounce and twang.',
        bpm: 90,
        durationSeconds: 90,
        xpValue: 115,
        focusPoints: [
          'Double stops: sixths and thirds give country music its "harmony" lead sound',
          'Let open strings ring between fretted notes — this is the open-string lick approach',
          'Aim for that "Telecaster twang" — bright, crisp, with swagger in the phrasing',
        ],
        selfAssessment: true,
      },
    ],
  },

  {
    id: 'country-rank-test-expert-pro',
    archetypeId: 'country',
    fromRank: 'expert',
    toRank: 'pro',
    label: 'Expert Gate: Full Country Flatpicking',
    songTitle: 'Foggy Mountain Breakdown — Full Arrangement',
    description:
      'Perform the classic Earl Scruggs–influenced flatpicking breakdown at full tempo, demonstrating bluegrass-level precision, stamina, and musical feel.',
    techniques: [
      { name: 'Flatpicking at Speed (150+ BPM)', branch: 'technique', nodeId: 'country-010' },
      { name: 'Carter Family Rhythm', branch: 'rhythm-timing', nodeId: 'country-009' },
      { name: 'Melodic Approach (playing melody on single strings)', branch: 'lead-improvisation', nodeId: 'country-011' },
      { name: 'Full Song Performance Stamina', branch: 'technique', nodeId: 'country-012' },
    ],
    nodeIds: ['country-009', 'country-010', 'country-011', 'country-012'],
    passingScore: 0.82,
    exercises: [
      {
        id: 'ex-country-rank-ep-1',
        type: 'technique',
        prompt: 'Play the Foggy Mountain Breakdown main lick (alternating bass + melody pattern) at 120 BPM and work up to 150 BPM. Every note must be distinct.',
        bpm: 120,
        bpmStart: 90,
        bpmGoal: 150,
        durationSeconds: 90,
        xpValue: 100,
        focusPoints: [
          'The alternating bass is the foundation — never sacrifice it for the melody runs',
          'At high tempos, use only downstrokes for the bass notes to stay consistent',
          'Keep the pick moving even when playing single notes — economy of motion is everything',
        ],
        selfAssessment: true,
      },
      {
        id: 'ex-country-rank-ep-2',
        type: 'performance',
        prompt: 'Perform the full Foggy Mountain Breakdown arrangement (intro–verse–break–verse–outro) at performance tempo. Play through without stopping even if a note slips.',
        bpm: 140,
        durationSeconds: 120,
        xpValue: 150,
        focusPoints: [
          'Performance mindset: keep moving through mistakes — stopping kills the feel',
          'The "break" section goes up the neck — know your positions cold before this test',
          'Make it groove: bluegrass at tempo is physically demanding but should sound effortless',
        ],
        selfAssessment: true,
      },
    ],
  },
];
