import type { TierTest } from '../../schema/TierTest';

export const COUNTRY_TIER_TESTS: TierTest[] = [
  {
    id: 'country-tier1-test',
    tierId: 1,
    archetypeId: 'country',
    label: 'Tier 1 Gate: Country Foundations',
    passingScore: 0.75,
    questions: [
      {
        id: 'ct1q1',
        prompt: 'In alternating bass-strum country rhythm, the bass note typically falls on:',
        options: ['Beats 2 and 4', 'Beats 1 and 3', 'All four beats', 'The off-beats only'],
        correctIndex: 1,
        explanation: 'Country rhythm guitar anchors the bass note on beats 1 and 3 (downbeats), while the chord strum lands on beats 2 and 4 — mirroring the roles of bass guitar and snare drum.',
      },
      {
        id: 'ct1q2',
        prompt: 'Hybrid picking combines:',
        options: [
          'Two picks held in the same hand',
          'A flatpick and the middle/ring fingers of the picking hand',
          'Fingerpicking only, no pick',
          'A pick and a slide simultaneously',
        ],
        correctIndex: 1,
        explanation: 'Hybrid picking uses a flatpick for downstrokes on lower strings while the middle and ring fingers pluck higher strings independently, enabling simultaneous bass-and-melody playing.',
      },
      {
        id: 'ct1q3',
        prompt: 'Which guitar is most associated with the classic twangy country sound?',
        options: ['Gibson Les Paul', 'Fender Stratocaster', 'Fender Telecaster', 'Gibson ES-335'],
        correctIndex: 2,
        explanation: 'The Fender Telecaster\'s bright, biting bridge pickup tone is synonymous with country guitar — from James Burton to Brad Paisley, it defines the genre\'s signature "spank."',
      },
      {
        id: 'ct1q4',
        prompt: 'What does it mean to "plant your thumb" while playing country rhythm?',
        options: [
          'Press the thumb against the neck for extra support',
          'Anchor the picking-hand thumb on a low string to play bass notes independently',
          'Use the thumb to mute all bass strings',
          'Rest the thumb on the guitar body for stability',
        ],
        correctIndex: 1,
        explanation: 'Planting the thumb on the low E or A string allows it to pick bass notes independently from the chord fingers, creating the alternating bass-and-strum texture central to country rhythm.',
      },
      {
        id: 'ct1q5',
        prompt: 'The key of G is extremely common in country music partly because:',
        options: [
          'It only uses minor chords',
          'The open strings of a standard-tuned guitar ring sympathetically with G major',
          'It is the highest key guitarists can play',
          'Country musicians prefer sharp keys exclusively',
        ],
        correctIndex: 1,
        explanation: 'G major is a "guitar-friendly" key — three of the six open strings (G, D, B) are chord tones of G major, so open strings ring sympathetically and add natural resonance.',
      },
    ],
    performanceExercise: {
      id: 'country-tier1-perf',
      type: 'performance',
      prompt: 'Play an open G major chord cleanly with all strings ringing and hold for 4 beats.',
      bpm: 80,
      durationSeconds: 10,
      xpValue: 0,
      targetNote: 'G2',
    },
  },
  {
    id: 'country-tier2-test',
    tierId: 2,
    archetypeId: 'country',
    label: 'Tier 2 Gate: Core Techniques',
    passingScore: 0.75,
    questions: [
      {
        id: 'ct2q1',
        prompt: 'Chicken pickin\' produces its signature pop sound by:',
        options: [
          'Strumming all strings with a heavy pick attack',
          'Using the middle fingernail to catch and snap a string sharply',
          'Picking only the highest string repeatedly',
          'Using a slide on the high strings',
        ],
        correctIndex: 1,
        explanation: 'The chicken-pickin\' snap comes from the middle finger (sometimes ring finger) catching a string with the nail and releasing it sharply — creating a percussive "pop" between fretted notes.',
      },
      {
        id: 'ct2q2',
        prompt: 'A pedal steel bend on guitar mimics the pedal steel guitar by:',
        options: [
          'Bending one string while holding an adjacent string stationary at a fixed pitch',
          'Using a glass bottleneck over all strings',
          'Bending all strings simultaneously one whole step',
          'Playing only natural harmonics',
        ],
        correctIndex: 0,
        explanation: 'The pedal steel effect requires bending one string up to meet an adjacent stationary string in pitch — the contrast between moving and fixed notes creates the characteristic weeping country tone.',
      },
      {
        id: 'ct2q3',
        prompt: 'The country shuffle feel compared to a rock straight-eighth feel is:',
        options: [
          'Exactly the same',
          'Slower and sadder',
          'Swung, with a long-short triplet subdivision',
          'Played with heavier string gauges',
        ],
        correctIndex: 2,
        explanation: 'Like blues shuffle, country shuffle swings the eighth notes — each beat is divided into a long-short pair based on a triplet feel. Country shuffle tends to be slightly tighter and more driving than blues shuffle.',
      },
      {
        id: 'ct2q4',
        prompt: 'What makes a unison bend special in country phrasing?',
        options: [
          'Both notes are played on the same string',
          'One string bends up to the same pitch as an adjacent fretted or open string',
          'Two strings are tuned to the exact same pitch',
          'The note is played twice in rapid succession',
        ],
        correctIndex: 1,
        explanation: 'A unison bend bends one string up until it matches the pitch of an adjacent string — when both strings ring simultaneously, they create a chorus-like shimmer that defines the pedal steel country sound.',
      },
      {
        id: 'ct2q5',
        prompt: 'Which artist is most closely associated with the Bakersfield country shuffle sound?',
        options: ['Garth Brooks', 'Buck Owens', 'Taylor Swift', 'Shania Twain'],
        correctIndex: 1,
        explanation: 'Buck Owens (with guitarist Don Rich) pioneered the Bakersfield Sound — a driving, Telecaster-forward, shuffle-based country style that influenced everyone from Merle Haggard to modern Americana artists.',
      },
    ],
  },
  {
    id: 'country-tier3-test',
    tierId: 3,
    archetypeId: 'country',
    label: 'Tier 3 Gate: Advanced Vocabulary',
    passingScore: 0.8,
    questions: [
      {
        id: 'ct3q1',
        prompt: 'Nashville tuning uses:',
        options: [
          'A capo at the 5th fret',
          'The four lower strings replaced with lighter octave-higher strings from a 12-string set',
          'All strings tuned a whole step up from standard',
          'Only the top three strings of the guitar',
        ],
        correctIndex: 1,
        explanation: 'Nashville tuning replaces strings 6–3 with the higher-octave strings from a 12-string guitar set, producing a shimmering, high-register tone often used in studio layering.',
      },
      {
        id: 'ct3q2',
        prompt: 'In open-G tuning, the open strings from low to high spell out:',
        options: ['E A D G B E', 'D G D G B D', 'G D G B D G', 'D A D G B E'],
        correctIndex: 1,
        explanation: 'Open-G tuning is D G D G B D — the low E is dropped to D, the A string is dropped to G, and the high E is dropped to D. All six open strings form a G major chord.',
      },
      {
        id: 'ct3q3',
        prompt: 'In a banjo roll pattern, notes are played:',
        options: [
          'All at once as a full chord strum',
          'In a rapid sequence across strings using pick and fingers independently',
          'Only on the two highest strings',
          'With a flatpick alone in very fast alternate picking',
        ],
        correctIndex: 1,
        explanation: 'Banjo rolls arpeggiate individual strings in a set pattern using the pick and two fingers independently — each string fires in sequence, creating a cascading, continuous sound.',
      },
      {
        id: 'ct3q4',
        prompt: 'Ghost notes in country lead phrasing are:',
        options: [
          'Notes played on the highest strings only',
          'Barely audible muted hits that fill rhythmic space between melodic notes',
          'Notes played with the slide at the 12th fret',
          'Very slow, sustained notes held for four beats',
        ],
        correctIndex: 1,
        explanation: 'Ghost notes are muted string hits (fret-hand muted) played between melodic notes to keep the rhythmic groove continuous — they\'re felt more than heard, adding percussive texture.',
      },
      {
        id: 'ct3q5',
        prompt: 'Slide guitar requires the slide to be positioned:',
        options: [
          'Behind the fret wire, like fretting a normal note',
          'Directly above the fret wire',
          'At the nut end of the neck',
          'On the picking hand instead of the fretting hand',
        ],
        correctIndex: 1,
        explanation: 'Unlike fretting, where the finger presses behind the fret, a slide must rest directly above the fret wire to produce the correct pitch. Pressing down causes buzzing; floating lightly gives the clean, singing tone.',
      },
    ],
  },
];
