import type { RankTest } from '../../schema/RankTest';

export const ROCKER_RANK_TESTS: RankTest[] = [
  {
    id: 'rocker-rank-test-beginner-novice',
    archetypeId: 'rocker',
    fromRank: 'beginner',
    toRank: 'novice',
    label: 'Beginner Gate: Rock Foundations',
    songTitle: 'Smoke on the Water — Main Riff',
    description:
      'Prove you can fret open chords cleanly and pick with control. Play the iconic 3-note riff using downstrokes, then strum a simple G–C–D progression.',
    techniques: [
      { name: 'Open Chords (G, C, D)', branch: 'harmony-chords', nodeId: 'rocker-001' },
      { name: 'Downstroke Picking', branch: 'technique', nodeId: 'rocker-002' },
      { name: 'Steady 8th-Note Strumming', branch: 'rhythm-timing' },
    ],
    nodeIds: ['rocker-001', 'rocker-002'],
    passingScore: 0.70,
    exercises: [
      {
        id: 'ex-rocker-rank-bg-1',
        type: 'technique',
        prompt: 'Play the Smoke on the Water riff using strict downstrokes on the low D–G–A string set. Keep each note separate and even.',
        bpm: 60,
        bpmStart: 50,
        bpmGoal: 70,
        durationSeconds: 60,
        xpValue: 60,
        focusPoints: [
          'Pick only downstrokes — no upstrokes yet',
          'Lift fingers cleanly between notes so they don\'t ring together',
          'Keep your pick angle consistent (about 45° to the string)',
        ],
        selfAssessment: true,
      },
      {
        id: 'ex-rocker-rank-bg-2',
        type: 'performance',
        prompt: 'Strum a G–C–D–G chord loop, two beats per chord. Stay in time and make sure every string rings clean.',
        bpm: 60,
        durationSeconds: 60,
        xpValue: 60,
        focusPoints: [
          'Press fingertips close to the fret wire — no buzzing',
          'Transition chords before the beat arrives, not on it',
          'Count "1-and-2-and" aloud as you strum',
        ],
        selfAssessment: true,
      },
    ],
  },

  {
    id: 'rocker-rank-test-novice-intermediate',
    archetypeId: 'rocker',
    fromRank: 'novice',
    toRank: 'intermediate',
    label: 'Novice Gate: Sweet Home Alabama',
    songTitle: 'Sweet Home Alabama — Main Riff',
    description:
      'Demonstrate control of power chords, palm muting, and the pentatonic scale by playing the classic D–C–G riff with authentic rock feel.',
    techniques: [
      { name: 'Alternate Picking', branch: 'technique', nodeId: 'rocker-002' },
      { name: 'Palm Muting', branch: 'technique', nodeId: 'rocker-004' },
      { name: 'D / C / G Chord Shapes', branch: 'harmony-chords', nodeId: 'rocker-001' },
      { name: 'String Skipping', branch: 'fretboard-theory', nodeId: 'rocker-005' },
      { name: 'Hammer-on & Pull-off', branch: 'technique' },
      { name: '8th-Note Subdivision', branch: 'rhythm-timing' },
    ],
    nodeIds: ['rocker-001', 'rocker-002', 'rocker-003', 'rocker-004', 'rocker-005'],
    passingScore: 0.75,
    exercises: [
      {
        id: 'ex-rocker-rank-ni-1',
        type: 'technique',
        prompt: 'Play the D–C–G chord progression with palm muting on the bass note of each chord, then open strum the rest. Repeat the 4-bar loop.',
        bpm: 80,
        bpmStart: 60,
        bpmGoal: 100,
        durationSeconds: 60,
        xpValue: 70,
        focusPoints: [
          'Rest the heel of your pick hand lightly on the bridge for the muted bass notes',
          'Keep the muting consistent — all muted notes should sound equally "chunky"',
          'Alternate pick throughout: down on beats 1 & 3, up on the "and"s',
        ],
        selfAssessment: true,
      },
      {
        id: 'ex-rocker-rank-ni-2',
        type: 'performance',
        prompt: 'Play the full Sweet Home Alabama main riff (D–C–G with the signature hammer-on fill) for 4 complete repetitions.',
        bpm: 90,
        durationSeconds: 60,
        xpValue: 80,
        focusPoints: [
          'Nail the timing of the hammer-on in the D chord — it lands on the "and" of beat 2',
          'Let the G chord ring open and full after the muted passage',
          'Think ahead to the next chord change — don\'t look at your hands',
        ],
        selfAssessment: true,
      },
    ],
  },

  {
    id: 'rocker-rank-test-intermediate-expert',
    archetypeId: 'rocker',
    fromRank: 'intermediate',
    toRank: 'expert',
    label: 'Intermediate Gate: Purple Haze',
    songTitle: 'Purple Haze — Intro & Verse Riff',
    description:
      'Show mastery of barre chords, string bending, and pentatonic lead phrasing through the Jimi Hendrix classic.',
    techniques: [
      { name: 'Barre Chords (E-shape)', branch: 'harmony-chords', nodeId: 'rocker-006' },
      { name: 'Whole-Step String Bend', branch: 'technique', nodeId: 'rocker-009' },
      { name: 'Pentatonic Lead Phrasing', branch: 'lead-improvisation', nodeId: 'rocker-008' },
      { name: 'Syncopated Rhythm Patterns', branch: 'rhythm-timing', nodeId: 'rocker-007' },
    ],
    nodeIds: ['rocker-006', 'rocker-007', 'rocker-008', 'rocker-009'],
    passingScore: 0.78,
    exercises: [
      {
        id: 'ex-rocker-rank-ie-1',
        type: 'technique',
        prompt: 'Play the E7#9 barre chord shape and execute the opening riff rhythm (the iconic syncopated figure). Keep the rhythm tight and the chord clean.',
        bpm: 80,
        bpmStart: 65,
        bpmGoal: 95,
        durationSeconds: 60,
        xpValue: 85,
        focusPoints: [
          'The syncopation falls on the "and" of beat 2 — feel it before you play it',
          'Mute unused strings with your fretting hand to keep the barre chord punchy',
          'Strumming hand stays loose — tension kills rhythmic feel',
        ],
        selfAssessment: true,
      },
      {
        id: 'ex-rocker-rank-ie-2',
        type: 'performance',
        prompt: 'Improvise a 12-bar solo over an E7 backing track. Include at least one whole-step bend that resolves in tune, and leave intentional space between phrases.',
        bpm: 90,
        durationSeconds: 90,
        xpValue: 115,
        focusPoints: [
          'Bend in tune — fret the target pitch first so your ear knows where to land',
          'Use silence: a two-beat rest between phrases is a musical statement',
          'Aim for at least three distinct phrases — not one long stream of notes',
        ],
        selfAssessment: true,
      },
    ],
  },

  {
    id: 'rocker-rank-test-expert-pro',
    archetypeId: 'rocker',
    fromRank: 'expert',
    toRank: 'pro',
    label: 'Expert Gate: Full Solo Mastery',
    songTitle: 'Comfortably Numb — Solo',
    description:
      'Demonstrate pro-level vibrato, sustained bends, and the ability to shape a full emotional arc over a slow solo. This is about feel and control, not speed.',
    techniques: [
      { name: 'Vibrato (controlled, even)', branch: 'technique', nodeId: 'rocker-010' },
      { name: 'Sweep Arpeggio', branch: 'technique', nodeId: 'rocker-011' },
      { name: 'Full Improvisation Arc', branch: 'lead-improvisation', nodeId: 'rocker-012' },
      { name: 'Dynamic Phrasing (quiet to intense)', branch: 'lead-improvisation' },
    ],
    nodeIds: ['rocker-010', 'rocker-011', 'rocker-012'],
    passingScore: 0.80,
    exercises: [
      {
        id: 'ex-rocker-rank-ep-1',
        type: 'technique',
        prompt: 'Play a slow minor arpeggio sweep (3-string Am shape) ascending and descending 8 times. Every note must ring individually — no blurring.',
        bpm: 60,
        bpmStart: 50,
        bpmGoal: 90,
        durationSeconds: 60,
        xpValue: 100,
        focusPoints: [
          'Roll your fretting finger across each note to prevent overlap',
          'The pick moves in ONE direction per sweep — don\'t let it hesitate',
          'Listen for evenness: each note should match the volume of the others',
        ],
        selfAssessment: true,
      },
      {
        id: 'ex-rocker-rank-ep-2',
        type: 'performance',
        prompt: 'Perform a 90-second improvised solo over a slow minor backing track. Start quietly, build to an intense peak, then resolve with vibrato on the final note.',
        bpm: 65,
        durationSeconds: 90,
        xpValue: 150,
        focusPoints: [
          'Shape the solo like a story: intro → build → climax → resolution',
          'Apply vibrato on sustained notes — it should be steady and intentional, not nervous',
          'Record yourself if possible and listen back for dynamics',
        ],
        selfAssessment: true,
      },
    ],
  },
];
