import type { TierTest } from '../../schema/TierTest';

export const ROCKER_TIER_TESTS: TierTest[] = [
  {
    id: 'rocker-tier1-test',
    tierId: 1,
    archetypeId: 'rocker',
    label: 'Tier 1 Gate: Rock Foundations',
    passingScore: 0.75,
    questions: [
      {
        id: 'r1q1',
        prompt: 'Which fingers form a standard open G major chord?',
        options: ['Fingers 1, 2, 3', 'Fingers 1, 3, 4', 'Fingers 2, 3, 4', 'Fingers 1, 2, 4'],
        correctIndex: 1,
        explanation: 'Open G major is typically fingered with fingers 2, 3, and 4 — but the most common rock fingering uses 1, 3, 4 to free finger 2 for open chord transitions.',
      },
      {
        id: 'r1q2',
        prompt: 'When using a pick, what is the most efficient motion for downstrokes on single strings?',
        options: ['Full arm movement', 'Wrist rotation with minimal arm movement', 'Finger-only movement', 'Shoulder-driven strokes'],
        correctIndex: 1,
        explanation: 'Efficient picking relies on wrist rotation — the arm anchors while the wrist drives the motion, reducing fatigue and increasing speed.',
      },
      {
        id: 'r1q3',
        prompt: 'What interval defines a power chord (5th chord)?',
        options: ['Minor third', 'Major third', 'Perfect fifth', 'Tritone'],
        correctIndex: 2,
        explanation: 'Power chords are built from the root and the perfect fifth (7 semitones up), giving them their open, ambiguous sound that works with heavy distortion.',
      },
      {
        id: 'r1q4',
        prompt: 'Palm muting is achieved by placing the picking hand palm:',
        options: ['Over the soundhole', 'On the frets near the nut', 'Lightly on the strings near the bridge', 'Across all strings at the 12th fret'],
        correctIndex: 2,
        explanation: 'Resting the palm lightly on the strings close to the bridge dampens sustain without killing the note entirely, creating the characteristic "chug" sound.',
      },
      {
        id: 'r1q5',
        prompt: 'What does BPM stand for?',
        options: ['Beats Per Measure', 'Bars Per Minute', 'Beats Per Minute', 'Bass Per Measure'],
        correctIndex: 2,
        explanation: 'BPM (Beats Per Minute) is the standard unit of tempo in music. 120 BPM = 2 beats per second.',
      },
    ],
    performanceExercise: {
      id: 'rocker-tier1-perf',
      type: 'performance',
      prompt: 'Play an open E major chord cleanly and hold for 4 beats. All strings should ring clearly.',
      bpm: 80,
      durationSeconds: 10,
      xpValue: 0,
      targetNote: 'E2',
    },
  },
  {
    id: 'rocker-tier2-test',
    tierId: 2,
    archetypeId: 'rocker',
    label: 'Tier 2 Gate: Rock Techniques',
    passingScore: 0.75,
    questions: [
      {
        id: 'r2q1',
        prompt: 'The minor pentatonic scale in the key of A contains which notes?',
        options: ['A C D E G', 'A B C D E', 'A C# E F# G#', 'A Bb C D Eb'],
        correctIndex: 0,
        explanation: 'A minor pentatonic: A C D E G — five notes (root, minor 3rd, 4th, 5th, minor 7th). This is the foundation of nearly all rock soloing.',
      },
      {
        id: 'r2q2',
        prompt: 'A barre chord requires:',
        options: ['Only two fingers', 'The index finger to fret all six strings at once', 'Only open strings', 'The pinky finger across all strings'],
        correctIndex: 1,
        explanation: 'Barre chords use the index finger as a movable capo across all (or most) strings, allowing any chord shape to be played in any key.',
      },
      {
        id: 'r2q3',
        prompt: 'What is the standard tuning of a guitar from low to high?',
        options: ['D A D G B E', 'E A D G B E', 'E B G D A E', 'A D G B E A'],
        correctIndex: 1,
        explanation: 'Standard tuning (low to high): E2 A2 D3 G3 B3 E4. This is the universal reference for most guitar instruction.',
      },
      {
        id: 'r2q4',
        prompt: 'In 4/4 time, how many beats does a dotted quarter note receive?',
        options: ['1 beat', '1.5 beats', '2 beats', '3 beats'],
        correctIndex: 1,
        explanation: 'A dot adds half the note\'s value — a quarter note = 1 beat, so a dotted quarter = 1 + 0.5 = 1.5 beats.',
      },
      {
        id: 'r2q5',
        prompt: 'The shuffle rhythm (used extensively in blues-rock) divides beats into:',
        options: ['Even 8th notes', 'Triplet feel with swing — long-short pairs', 'Straight 16th notes', 'Groups of five'],
        correctIndex: 1,
        explanation: 'Shuffle feel swings 8th notes — the first is long (2/3 of the beat) and the second is short (1/3), derived from triplets: play beats 1 and 3 of each triplet.',
      },
    ],
  },
  {
    id: 'rocker-tier3-test',
    tierId: 3,
    archetypeId: 'rocker',
    label: 'Tier 3 Gate: Lead Playing',
    passingScore: 0.8,
    questions: [
      {
        id: 'r3q1',
        prompt: 'A whole-step bend raises the pitch by:',
        options: ['1 semitone', '2 semitones', '3 semitones', '4 semitones'],
        correctIndex: 1,
        explanation: 'A whole-step (full-step) bend raises pitch by 2 semitones — equivalent to moving up 2 frets. A half-step bend raises by 1 semitone.',
      },
      {
        id: 'r3q2',
        prompt: 'Vibrato on guitar is created by:',
        options: ['Picking the string repeatedly', 'Repeatedly bending the string slightly sharp and releasing in a controlled rhythm', 'Using the tremolo bar', 'Tapping the body'],
        correctIndex: 1,
        explanation: 'Finger vibrato oscillates pitch by repeatedly pushing/pulling the string across the fretboard. The rate and depth determine the character of the vibrato.',
      },
      {
        id: 'r3q3',
        prompt: 'What does "legato" mean in guitar technique?',
        options: ['Playing with a heavy pick attack', 'Playing notes smoothly using hammer-ons and pull-offs', 'Playing with palm muting', 'Playing arpeggiated chords'],
        correctIndex: 1,
        explanation: 'Legato = smooth and connected. In guitar, this means using hammer-ons and pull-offs to connect notes without picking each one individually.',
      },
      {
        id: 'r3q4',
        prompt: 'The pentatonic scale has how many notes per octave?',
        options: ['4', '5', '6', '7'],
        correctIndex: 1,
        explanation: 'Pentatonic = five notes (penta = five). The minor pentatonic: root, minor 3rd, 4th, 5th, minor 7th.',
      },
      {
        id: 'r3q5',
        prompt: 'Rock rhythm guitar in 4/4 typically emphasizes the:',
        options: ['1 and 3 beats (downbeats)', '2 and 4 beats (backbeats)', 'All 4 beats equally', 'Only the 1 beat'],
        correctIndex: 1,
        explanation: 'Rock (like most popular music) emphasizes beats 2 and 4 — the backbeats. The snare drum typically lands there, creating the characteristic "drive" of rock.',
      },
    ],
  },
];
