import type { RankTest } from '../../schema/RankTest';

export const CLASSICAL_RANK_TESTS: RankTest[] = [
  {
    id: 'classical-rank-test-beginner-novice',
    archetypeId: 'classical',
    fromRank: 'beginner',
    toRank: 'novice',
    label: 'Beginner Gate: Right-Hand Foundation',
    songTitle: 'Romanza — First Section',
    description:
      'Demonstrate correct rest-stroke and free-stroke technique with consistent tone production using the thumb and fingers.',
    techniques: [
      { name: 'Rest Stroke (apoyando)', branch: 'technique', nodeId: 'classical-001' },
      { name: 'Free Stroke (tirando)', branch: 'technique', nodeId: 'classical-002' },
      { name: 'p-i-m-a Fingering', branch: 'technique', nodeId: 'classical-001' },
    ],
    nodeIds: ['classical-001', 'classical-002'],
    passingScore: 0.70,
    exercises: [
      {
        id: 'ex-classical-rank-bg-1',
        type: 'technique',
        prompt: 'Play a rest-stroke melody on the B string (E–F#–G–A–B) while holding a C chord with your fretting hand. Each melody note should ring clear and full.',
        bpm: 55,
        bpmStart: 45,
        bpmGoal: 70,
        durationSeconds: 60,
        xpValue: 60,
        focusPoints: [
          'Rest stroke: after plucking, your finger rests on the next lower string',
          'Nail angle: the right-hand nail should make first contact with the string, not the flesh',
          'Keep the fretting hand chord held — don\'t let notes buzz as you play melody',
        ],
        selfAssessment: true,
      },
      {
        id: 'ex-classical-rank-bg-2',
        type: 'performance',
        prompt: 'Play the arpeggiated accompaniment pattern for Romanza (p on bass, then i-m-a on treble strings) for 8 bars. Keep the thumb and fingers independent.',
        bpm: 60,
        durationSeconds: 60,
        xpValue: 60,
        focusPoints: [
          'Thumb (p) plays bass notes — keep it separate from the finger motion',
          'Fingers curve and pluck through the string, not across it',
          'Maintain consistent nail contact angle — no scratching or thin sound',
        ],
        selfAssessment: true,
      },
    ],
  },

  {
    id: 'classical-rank-test-novice-intermediate',
    archetypeId: 'classical',
    fromRank: 'novice',
    toRank: 'intermediate',
    label: 'Novice Gate: Leyenda (Asturias)',
    songTitle: 'Asturias (Leyenda) — Opening Tremolo Section',
    description:
      'Demonstrate the tremolo technique (p-a-m-i) with consistent tone and the ability to sustain the bass melody while the treble tremolo flows.',
    techniques: [
      { name: 'Tremolo (p-a-m-i pattern)', branch: 'technique', nodeId: 'classical-004' },
      { name: 'Simultaneous Bass & Melody', branch: 'technique', nodeId: 'classical-003' },
      { name: 'Left-Hand Legato (slurs)', branch: 'technique', nodeId: 'classical-005' },
      { name: 'Position Shifts', branch: 'fretboard-theory' },
    ],
    nodeIds: ['classical-003', 'classical-004', 'classical-005'],
    passingScore: 0.75,
    exercises: [
      {
        id: 'ex-classical-rank-ni-1',
        type: 'technique',
        prompt: 'Practice the tremolo pattern (p-a-m-i) on the open B string while your thumb alternates bass notes on E and A. Run for 90 seconds without stopping.',
        bpm: 60,
        bpmStart: 50,
        bpmGoal: 80,
        durationSeconds: 90,
        xpValue: 70,
        focusPoints: [
          'The tremolo fingers (a-m-i) should feel like a smooth, rolling wave — no accents',
          'The thumb is independent — it doesn\'t affect the tremolo timing',
          'Listen for evenness: all 3 tremolo notes should be identical in volume',
        ],
        selfAssessment: true,
      },
      {
        id: 'ex-classical-rank-ni-2',
        type: 'performance',
        prompt: 'Play the opening 16 bars of Asturias with tremolo on the E string and the bass melody below. Focus on making the melody line sing through the texture.',
        bpm: 65,
        durationSeconds: 90,
        xpValue: 80,
        focusPoints: [
          'The bass melody (thumb) is the main voice — bring it forward dynamically',
          'Let the tremolo be a "shimmer" underneath — present but not dominating',
          'Position shifts: pivot on the fingertip that stays in place, swing the others',
        ],
        selfAssessment: true,
      },
    ],
  },

  {
    id: 'classical-rank-test-intermediate-expert',
    archetypeId: 'classical',
    fromRank: 'intermediate',
    toRank: 'expert',
    label: 'Intermediate Gate: Recuerdos de la Alhambra',
    songTitle: 'Recuerdos de la Alhambra — Full Performance',
    description:
      'Perform the complete tremolo study cleanly at a musical tempo, with dynamic shaping and expressive phrasing across all sections.',
    techniques: [
      { name: 'Extended Tremolo Endurance', branch: 'technique', nodeId: 'classical-007' },
      { name: 'Dynamic Control (pp–mf)', branch: 'technique', nodeId: 'classical-008' },
      { name: 'Rubato & Musical Phrasing', branch: 'lead-improvisation', nodeId: 'classical-009' },
      { name: 'Barré Chords in High Positions', branch: 'harmony-chords', nodeId: 'classical-006' },
    ],
    nodeIds: ['classical-006', 'classical-007', 'classical-008', 'classical-009'],
    passingScore: 0.78,
    exercises: [
      {
        id: 'ex-classical-rank-ie-1',
        type: 'technique',
        prompt: 'Play 32 bars of continuous tremolo in A minor, controlling volume from pp to mf and back. The right hand must not tire or tense up.',
        bpm: 70,
        bpmStart: 60,
        bpmGoal: 85,
        durationSeconds: 120,
        xpValue: 90,
        focusPoints: [
          'Lightness is the key to endurance — use the minimum force needed for the tone',
          'Breathe with the phrases: let your shoulders drop on long notes',
          'Dynamic control comes from nail contact depth, not arm tension',
        ],
        selfAssessment: true,
      },
      {
        id: 'ex-classical-rank-ie-2',
        type: 'performance',
        prompt: 'Perform the full piece (or at least 3 complete sections ABAB). Apply rubato to the melodic peaks — let time breathe.',
        bpm: 72,
        durationSeconds: 180,
        xpValue: 110,
        focusPoints: [
          'Let the A section melody float above the tremolo — it should feel like it\'s being sung',
          'B section: the harmonics or higher position chords need extra clarity',
          'Musical phrasing: aim for phrases, not just notes — think in 4-bar sentences',
        ],
        selfAssessment: true,
      },
    ],
  },

  {
    id: 'classical-rank-test-expert-pro',
    archetypeId: 'classical',
    fromRank: 'expert',
    toRank: 'pro',
    label: 'Expert Gate: Chaconne Movements',
    songTitle: 'Bach Chaconne (BWV 1004) — Selected Variations',
    description:
      'Navigate polyphonic writing, advanced barré positions, and sustained musical architecture across Bach\'s most demanding guitar work.',
    techniques: [
      { name: 'Polyphonic Voicing (independent lines)', branch: 'music-theory', nodeId: 'classical-010' },
      { name: 'Advanced Barré (VIII–XII fret)', branch: 'harmony-chords', nodeId: 'classical-011' },
      { name: 'Sustained Musical Architecture', branch: 'lead-improvisation', nodeId: 'classical-012' },
    ],
    nodeIds: ['classical-010', 'classical-011', 'classical-012'],
    passingScore: 0.82,
    exercises: [
      {
        id: 'ex-classical-rank-ep-1',
        type: 'technique',
        prompt: 'Play 16 bars of a Bach-style polyphonic passage (soprano and bass as separate independent voices). Make each voice line identifiable by dynamics.',
        bpm: 56,
        bpmStart: 48,
        bpmGoal: 68,
        durationSeconds: 90,
        xpValue: 100,
        focusPoints: [
          'Soprano voice: slightly louder, played with free stroke using the nail',
          'Bass voice: steady and grounded, played with thumb rest stroke',
          'Middle voices: present but supporting — never louder than soprano',
        ],
        selfAssessment: true,
      },
      {
        id: 'ex-classical-rank-ep-2',
        type: 'performance',
        prompt: 'Perform 3 complete variations from the Chaconne theme (at least 48 bars). The harmonic arch must be clear — listener should feel the tension and release.',
        bpm: 58,
        durationSeconds: 180,
        xpValue: 150,
        focusPoints: [
          'The Chaconne builds and releases over entire sections — think in 16-bar arcs, not individual measures',
          'Every ornament must be rhythmically precise and serve the phrase',
          'The final chord of each variation is a rhetorical point — arrive there with intention',
        ],
        selfAssessment: true,
      },
    ],
  },
];
